# Generated by Django 4.1.4 on 2022-12-20 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Info',
            new_name='Surah',
        ),
    ]
