# Generated by Django 4.1.4 on 2022-12-20 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_info_surah'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='surah',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Surah'},
        ),
    ]
